import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GridFloor from "@/components/grid";
import Footer from "@/components/footer/footer";
import { ScrollProvider } from "@/context/ScrollContext";
import clsx from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "antialiased h-svh"
        )}
      >
        {/* Grid overlay scroll pane */}

        {/* Main content scroll pane */}
        <div className="main-content flex-1 min-h-0 h-svh overflow-y-auto snap-y snap-mandatory text-black dark:text-white main-scroll-pane">
          <div className="fixed top-0 left-0 w-full h-full pointer-events-none z-0 hidden dark:block">
            <GridFloor />
          </div>

          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
